#ifndef REACT_WINDOW_H
#define REACT_WINDOW_H

typedef enum {
  RW_ALIGN_TOP_LEFT,
  RW_ALIGN_TOP_CENTER,
  RW_ALIGN_TOP_RIGHT,
  RW_ALIGN_LEFT,
  RW_ALIGN_CENTER,
  RW_ALIGN_RIGHT,
  RW_ALIGN_BOTTOM_LEFT,
  RW_ALIGN_BOTTOM_CENTER,
  RW_ALIGN_BOTTOM_RIGHT,
} rw_align_e;

#endif
